WebApp/Models/ApiModels/NewsApiModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models.ApiModels
{
    public class NewsApiModel
    {
        public DateTime updateTime { get; set; }

        public List<NewsDataModel> News { get;set; }

    }

    public class NewsDataModel
    {
        public string chtmessage { get; set; }
        public string engmessage { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public string updatetime { get; set; }
        public string content { get; set; }
        public string url { get; set; }
    }
}

WebApp/Models/Responses/BaseResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models.Responses
{
    public class BaseResponse
    {
        public bool Success { get; set; }
        public string Message { get; set; }
    }
}

WebApp/Models/Responses/NewsApiResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApp.Models.ApiModels;

namespace WebApp.Models.Responses
{
    public class NewsApiResponse : BaseResponse
    {

        public List<NewsDataModel> Data { get; set; }

        public NewsApiResponse()
        {
            Data = new List<NewsDataModel>();
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApp/Controllers/NewsApiController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.ApiModels;
using WebApp.Models.Responses;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class NewsApiController : Controller
    {
        private NewsApiService _NewsApiService;

        public NewsApiController()
        {
            _NewsApiService = new NewsApiService();
        }

        public async Task<JsonResult> GetApiDataLists()
        {
            var result = new NewsApiResponse();
            string NewsApiUrl = "https://tcgbusfs.blob.core.windows.net/dotapp/news.json";

            using (HttpClient client = new HttpClient())
            {
                try
                {
                    client.Timeout = TimeSpan.FromSeconds(10);
                    HttpResponseMessage response = await client.GetAsync(new Uri(NewsApiUrl));
                    response.EnsureSuccessStatusCode();

                    string responseBody = await response.Content.ReadAsStringAsync();
                    responseBody = responseBody.Replace("\r\n", string.Empty);
                    var data = JsonConvert.DeserializeObject<NewsApiModel>(responseBody);

                    if (data.News.Count > 0)
                    {
                        result = _NewsApiService.InsertData(data.News);
                    }
                    else
                    {
                        result.Success = true;
                        result.Message = "Api存取成功，尚無回傳資料";
                    } 
                }
                catch (Exception ex)
                {
                    result.Success = false;
                    result.Message = "存取api失敗";
                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "臺北市即時交通訊息";
}

<style>
    tbody td {
        word-break: break-all;
        min-width: 90px;
        max-width: 200px;
    }
</style>

<div class="row">
    <div class="col-xs-12">
        <h1>臺北市即時交通訊息</h1>        
    </div>
    <div class="row">
        <div class="col-4">
            <button type="button" class="btn btn-primary btn-lg m-1" onclick="GetApiData();">取api資料並儲存</button>
            <button id="Clear" type="button" class="btn btn-outline-secondary btn-lg m-1" onclick="ClearTable();">清除</button>
        </div>
        <div class="col-8">
            <div id="Alert" class="alert" role="alert" style="display:none;"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <table id="dataTable" class="table table-bordered table-hover">
                <thead class="table">
                    <tr>
                        <th>中文訊息</th>
                        <th>英文訊息</th>
                        <th>開始時間</th>
                        <th>結束時間</th>
                        <th>更新時間</th>
                        <th>內容</th>
                        <th>連結網址</th>
                    </tr>
                </thead>
                <tbody>
                    <tr id="NoData">
                        <td class="text-center" colspan="7">無資料</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>   
</div>

<script>
    function ShowAlert(success, message) {
        var alert = document.getElementById("Alert");
        alert.classList.remove("alert-danger", "alert-success");        
        alert.innerHTML = message;        
        alert.style.display = "block";
        if (success) {
            alert.classList.add("alert-success");
            setTimeout(HideAlert, 3000);
        }
        else {
            alert.classList.add("alert-danger");
        }
    }

    function HideAlert() {
        var alert = document.getElementById("Alert");
        alert.classList.remove("alert-danger", "alert-success");
        alert.style.display = "none";
    }

    function ClearTable() {
        //清除tbody內容
        var tbody = document.getElementsByTagName("tbody")[0];
        tbody.innerHTML = "";

        //顯示無資料行
        var tr = document.createElement("tr");
        tr.setAttribute("id", "NoData");
        var td = document.createElement("td");
        td.setAttribute("colspan", 7);
        td.classList.add("text-center");
        td.innerHTML = "無資料";
        tr.append(td);
        tbody.append(tr);

        //清除提示
        HideAlert();
    }

    function GetApiData() {
        fetch('@Url.Action("GetApiDataLists", "NewsApi")')
            .then(function (response) {
                return response.json();
            })            
            .then(function (result) {
                if (result.Data.length > 0) {
                    //隱藏無資料行
                    var noData = document.getElementById("NoData");
                    if (noData) {
                        noData.hidden = true;
                    }

                    var tbody = document.getElementsByTagName("tbody")[0];
                    for (let i = 0; i < result.Data.length; i++) {
                        var tr = document.createElement("tr");
                        for (let attr of Object.keys(result.Data[i])) {
                            var td = document.createElement("td");
                            if (attr == 'url' && result.Data[i][attr]) {
                                var url = document.createElement("a");
                                url.setAttribute('href', result.Data[i][attr]);
                                url.innerHTML = "前往連結";
                                url.classList.add("link-primary");
                                td.append(url);
                            }
                            else if (attr == 'content' && result.Data[i][attr].length > 40) {
                                var view = document.createElement("a");
                                view.innerHTML = "查看更多"
                                view.classList.add("link-secondary");
                                view.setAttribute('onclick', "alert('" + result.Data[i][attr] + "')");
                                td.append(result.Data[i][attr].substring(0, 40) + " .... ");
                                td.append(view);
                            }
                            else {
                                td.innerHTML = result.Data[i][attr];
                            }
                            tr.append(td);
                        }
                        tbody.append(tr);
                    }
                }
                ShowAlert(result.Success, result.Message);
            })
            .catch((error) => {
                console.log(`Error: ${error}`);
            })
    }

    window.onload = function () {

    }
</script>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切換導覽" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("首頁", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-right">資料來源: <a href="https://data.gov.tw/dataset/128476">臺北市即時交通訊息</a></p>
        </footer>
    </div>
</body>
</html>